name: DevSecOps Pipeline

on:
  push:
    branches:
      - master
      - main

jobs:
  sonarqube:
    name: SonarQube Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2.3.0
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

  zap_scan:
    runs-on: ubuntu-latest
    needs: sonarqube
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: ZAP Scan
        uses: zaproxy/action-baseline@latest
        with:
          token: ${{ secrets.GIT_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: ${{ secrets.TARGET_URL }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
