name: CI/CD workflow for Maven Build and Sonar Code scan
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
  zap_scan:
    runs-on: ubuntu-latest
    needs: sonarqube
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: ZAP Scan
        uses: zaproxy/action-baseline@latest
        with:
          token: ${{ secrets.GIT_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: ${{ secrets.TARGET_URL }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
