name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

   #   - name: Set up Node.js
  #      uses: actions/setup-node@v3
    #    with:
     #     node-version: '16'
     # - name: Install dependencies
       # run: npm install
      - name: Build application
        run: npm run build
    continue-on-error: true  # Continue even if the build fails

  sast:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11 # Required for SonarQube scanner
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Install SonarQube Scanner
        run: |
          wget -qO- https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip | jar x
          export PATH="$PATH:$(pwd)/sonar-scanner-4.8.0.2856-linux/bin"

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Add your SonarQube token in GitHub Secrets
        run: |
          sonar-scanner \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://5.180.151.215:9000/ \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    continue-on-error: true  # Continue even if the SAST scan fails

  dast:
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OWASP ZAP
        run: sudo apt-get install zaproxy

      - name: Run DAST (OWASP ZAP)
        run: |
          zap-cli start
          zap-cli open-url http://localhost:3000 # Adjust based on your application
          zap-cli spider http://localhost:3000
          zap-cli active-scan http://localhost:3000
          zap-cli alerts -l High

      - name: Stop OWASP ZAP
        run: zap-cli shutdown
    continue-on-error: true  # Continue even if the DAST scan fails
